


SELECT MES_SHOPFLOOR_NAME as 生产车间,AREA_NAME as 生产单元,
       ZENGGUO_NAME as 甑锅,ZENGGUO_CODE as 甑锅编号,
       MES_ZENGGUO_RECORD.id AS 甑锅执行记录ID,
       CASE
           WHEN MES_ZENGGUO_RECORD.ZAOPEI_TYPE = 1 THEN '面糟'
           WHEN MES_ZENGGUO_RECORD.ZAOPEI_TYPE = 2 THEN '中上粮糟'
           WHEN MES_ZENGGUO_RECORD.ZAOPEI_TYPE = 3 THEN '下层粮糟'
           WHEN MES_ZENGGUO_RECORD.ZAOPEI_TYPE = 4 THEN '双轮底（丢糟：水醅）'
           WHEN MES_ZENGGUO_RECORD.ZAOPEI_TYPE = 5 THEN '红糟'
           WHEN MES_ZENGGUO_RECORD.ZAOPEI_TYPE = 6 THEN '升池糟'
           ELSE '未知'
           END AS 糟醅类型,
       CASE
           WHEN MES_ZENGGUO_RECORD.ENUM_SHIFT = 'DAY_SHIFT' THEN '白班'
           WHEN MES_ZENGGUO_RECORD.ENUM_SHIFT = 'SHORT_NIGHT_SHIFT' THEN '小夜班'
           WHEN MES_ZENGGUO_RECORD.ENUM_SHIFT = 'LONG_NIGHT_SHIFT' THEN '大夜班'
           ELSE '未知'
           END AS 班次,
       MES_SHIFT_TEAM.TEAM_NAME as 班组,
       MES_ZENGGUO_RECORD.ZENG_SEQUENCE AS 甑次,
         MES_ZENGGUO_RECORD.START_TIME_TOTAL AS 锅次开始时间,
            MES_ZENGGUO_RECORD.END_TIME_TALL AS 锅次结束时间,
            MES_ZENGGUO_RECORD.SHANGZENG_XIAOLV AS 装甑效率,
            MES_ZENGGUO_RECORD.SHANGZENG_XIELV AS L12斜率,
         MES_ZENGGUO_RECORD.START_TIME_DEVICE_SHANG_ZENG AS 上甑开始时间,
            MES_ZENGGUO_RECORD.START_TIME_KAGAI AS 卡盖溜酒开始时间,
            MES_ZENGGUO_RECORD.END_TIME_LIUJIU AS 溜酒结束时间,
            MES_ZENGGUO_RECORD.RUNLIANG_ADD_WATER_DOWN AS 下半甑润粮加水量,
            MES_ZENGGUO_RECORD.RUNLIANG_ADD_WATER_UP AS 上半甑润粮加水量,
            MES_ZENGGUO_RECORD.RUNLIANG_DURATION_DOWN AS 下半甑润粮时长,
            MES_ZENGGUO_RECORD.RUNLIANG_DURATION_UP AS 上半甑润粮时长,
            MES_ZENGGUO_RECORD.ZAOPEI_QTY_DOWN AS 下半甑糟醅量,
            MES_ZENGGUO_RECORD.ZAOPEI_QTY_UP AS 上半甑糟醅量,
            MES_ZENGGUO_RECORD.DAOKE_QTY_DOWN AS 下半甑稻壳添加量,
            MES_ZENGGUO_RECORD.DAOKE_QTY_UP AS 上半甑稻壳添加量,
            MES_ZENGGUO_RECORD.LIANGSHI_QTY_DOWN AS 下半甑粮食添加量,
            MES_ZENGGUO_RECORD.LIANGSHI_QTY_UP AS 上半甑粮食添加量,
        CASE
            WHEN MES_ZENGGUO_RECORD.LIANGSHI_TYPE_DOWN = 0 THEN '粗粮'
            WHEN MES_ZENGGUO_RECORD.LIANGSHI_TYPE_DOWN = 1 THEN '细粮'
            ELSE '未知'
            END AS 下半甑粮食类型,
        CASE
            WHEN MES_ZENGGUO_RECORD.LIANGSHI_TYP_UP = 0 THEN '粗粮'
            WHEN MES_ZENGGUO_RECORD.LIANGSHI_TYP_UP = 1 THEN '细粮'
            ELSE '未知'
            END AS 上半甑粮食类型,
            MES_ZENGGUO_RECORD.JIAOCHI_LAYER_DOWN AS 下半甑糟醅窖池层,
            MES_ZENGGUO_RECORD.JIAOCHI_LAYER_UP AS 上半甑糟醅窖池层,
            MES_ZENGGUO_RECORD.ZHUANGZENG_LAYER AS 上甑层数,
            MES_ZENGGUO_RECORD.SHANGZENG_DURATION AS 上甑时长,
            MES_ZENGGUO_RECORD.SHANGZENG_HEIGHT AS 上甑高度,
            MES_ZENGGUO_RECORD.JIEJIU_DURATION_FIRST_CLASS AS 一级酒接酒时长,
            MES_ZENGGUO_RECORD.JIEJIU_DURATION_SECOND_CLASS AS 二级酒接酒时长,
            MES_ZENGGUO_RECORD.JIEJIU_DURATION_THIRD_CLASS AS 三级酒接酒时长,
            MES_ZENGGUO_RECORD.JIEJIU_DURATION_FEISHUI AS 酒尾酒接酒时长,
            MES_ZENGGUO_RECORD.LIANGSHUI_ADD_QTY AS 晾水添加量,
            MES_ZENGGUO_RECORD.HUISHOUDIGUO_WATER_ADD_QTY AS 回收底锅水添加量,
            MES_ZENGGUO_RECORD.HOT_WATER_ADD_QTY AS 热水添加量,
            MES_ZENGGUO_RECORD.JIUWEI_ADD_QTY AS 酒尾添加量,
            MES_ZENGGUO_RECORD.HUANGSHUI_ADD_QTY AS 黄水添加量,
            MES_ZENGGUO_RECORD.ENERGY_QI_SHANGZENG AS 上甑耗汽量,
            MES_ZENGGUO_RECORD.ENERGY_QI_ZHENGLIU AS 蒸馏耗汽量,
            MES_ZENGGUO_RECORD.LIUJIU_ADD_ZHENGZHU_DURATION AS 馏酒蒸煮总时长,
       MES_ZENGGOU_PHASE_CONFIG.PHASE_NAME AS 过程阶段名称,
       MES_ZENGGUO_RECORD.MES_START_TIME_TOTAL AS 过程阶段开始时间,
         MES_ZENGGUO_RECORD.PHASE_END_TIME_TOTAL AS 过程阶段结束时间,
         MES_ZENGGUO_RECORD.PHASE_DURATION AS 过程阶段时长,
       MES_ZENG_SUM_DATA.TANLIANG_ZAOPEI_WEIGHT AS 糟醅重量,
       MES_ZENG_SUM_DATA.TANLIANG_JIAQU_WEIGHT AS 加曲重量,
       MES_ZENG_SUM_DATA.TANLIANG_MAX_TEMP AS 摊晾最高温度,
       MES_ZENG_SUM_DATA.TANLIANG_MIN_TEMP AS 摊晾最低温度,
       MES_ZENG_SUM_DATA.TANLIANG_AVG_TEMP AS 摊晾平均温度
FROM MES_ZENGGUO_RECORD
         LEFT JOIN MES_ZENGTONG ON MES_ZENGGUO_RECORD.MES_ZENGGUO_ID = MES_ZENGTONG.id
         LEFT JOIN MES_AREA ON MES_ZENGTONG.MES_AREA_ID = MES_AREA.id
         LEFT JOIN MES_SHOPFLOOR  on MES_AREA.MES_SHOPFLOOR_ID = MES_SHOPFLOOR.id
         LEFT JOIN MES_ZENG_SUM_DATA ON MES_ZENGGUO_RECORD.SUM_DATA_RECORD_ID = MES_ZENG_SUM_DATA.id
         LEFT JOIN MES_SHIFT_TEAM on MES_SHIFT_TEAM.ID = MES_ZENGGUO_RECORD.SHIFT_TEAM_ID
        Left join MES_ZENGGOU_PHASE_CONFIG on MES_ZENGGOU_PHASE_CONFIG.id = MES_ZENGGUO_RECORD.ZENGGUO_PHASE_ID
WHERE MES_ZENGGUO_RECORD.END_TIME_TALL > '2022-10-24T13:41:39'
